"""
Report Tools (16-17)
====================
Security report generation tools.
"""

import json
import logging
from datetime import datetime
from typing import Optional

from sap.odata_client import SAPODataClient
from tools.security_tools import SecurityTools
from tools.basis_tools import BasisTools

logger = logging.getLogger("syntaai-mcp.reports")


class ReportTools:
    """Report generation tools."""

    def __init__(self, client: SAPODataClient):
        self.client = client
        self._security = SecurityTools(client)
        self._basis = BasisTools(client)

    # ─── Tool 16: Generate Security Excel ────────────────────────────────

    async def generate_security_excel(self, report_type: str = "full_report") -> str:
        """Generate a comprehensive security report (data for Excel export)."""

        report_data = {
            "report_type": report_type,
            "generated_at": datetime.now().isoformat(),
            "generated_by": "SyntaAI MCP Server (OData Edition)",
            "sections": []
        }

        if report_type in ("full_report", "user_report"):
            # SAP_ALL users
            sap_all = await self._security.check_sap_all_users()
            report_data["sections"].append({
                "name": "SAP_ALL/SAP_NEW Users",
                "data": sap_all
            })

            # Dormant users
            dormant = await self._security.get_dormant_users(90)
            report_data["sections"].append({
                "name": "Dormant Users (90+ days)",
                "data": dormant
            })

            # Locked users
            locked = await self._security.get_locked_users()
            report_data["sections"].append({
                "name": "Locked Users",
                "data": locked
            })

            # Default users
            defaults = await self._security.check_default_users()
            report_data["sections"].append({
                "name": "Default User Status",
                "data": defaults
            })

            # Users without roles
            no_roles = await self._security.check_users_no_roles()
            report_data["sections"].append({
                "name": "Users Without Roles",
                "data": no_roles
            })

        if report_type in ("full_report", "role_report"):
            # Critical tcodes
            critical = await self._security.check_critical_tcodes()
            report_data["sections"].append({
                "name": "Critical Transaction Code Access",
                "data": critical
            })

            # SoD violations
            sod = await self._security.check_sod_violations()
            report_data["sections"].append({
                "name": "Segregation of Duties Violations",
                "data": sod
            })

        if report_type in ("full_report", "compliance_report"):
            # Password policy
            pwd = await self._security.check_password_policy()
            report_data["sections"].append({
                "name": "Password Policy Compliance",
                "data": pwd
            })

            # System parameters
            params = await self._basis.get_system_parameters()
            report_data["sections"].append({
                "name": "Security Parameters",
                "data": params
            })

        # Build report output
        output = f"📊 SAP Security Report - {report_type.replace('_', ' ').title()}\n"
        output += f"Generated: {report_data['generated_at']}\n"
        output += "=" * 60 + "\n\n"

        for section in report_data["sections"]:
            output += f"── {section['name']} ──\n"
            output += section["data"] + "\n\n"

        output += "=" * 60 + "\n"
        output += "Report generated by SyntaAI SAP Security MCP Server (OData Edition)\n"
        output += "https://syntaai.com"

        return output

    # ─── Tool 17: Risk Summary ───────────────────────────────────────────

    async def generate_risk_summary(self) -> str:
        """Generate a comprehensive risk assessment summary."""

        findings = {
            "critical": [],
            "high": [],
            "medium": [],
            "low": [],
        }

        # Check SAP_ALL users
        try:
            sap_all = await self._security.check_sap_all_users()
            if "CRITICAL" in sap_all or "🚨" in sap_all:
                findings["critical"].append("Users with SAP_ALL/SAP_NEW profiles detected")
        except Exception as e:
            logger.warning(f"SAP_ALL check failed: {e}")

        # Check default users
        try:
            defaults = await self._security.check_default_users()
            if "UNLOCKED" in defaults:
                findings["critical"].append("Default SAP users are unlocked")
        except Exception as e:
            logger.warning(f"Default users check failed: {e}")

        # Check SoD violations
        try:
            sod = await self._security.check_sod_violations()
            if "violations found" in sod:
                findings["high"].append("Segregation of Duties violations detected")
        except Exception as e:
            logger.warning(f"SoD check failed: {e}")

        # Check dormant users
        try:
            dormant = await self._security.get_dormant_users(90)
            if "dormant users" in dormant:
                findings["medium"].append("Dormant user accounts found (90+ days inactive)")
        except Exception as e:
            logger.warning(f"Dormant check failed: {e}")

        # Check password policy
        try:
            pwd = await self._security.check_password_policy()
            if "⚠️" in pwd:
                findings["high"].append("Password policy does not meet security standards")
        except Exception as e:
            logger.warning(f"Password policy check failed: {e}")

        # Check critical tcodes
        try:
            tcodes = await self._security.check_critical_tcodes()
            if "critical tcode" in tcodes:
                findings["high"].append("Users with critical transaction code access")
        except Exception as e:
            logger.warning(f"Critical tcode check failed: {e}")

        # Check users without roles
        try:
            no_roles = await self._security.check_users_no_roles()
            if "without role" in no_roles:
                findings["low"].append("Active users without role assignments (orphaned accounts)")
        except Exception as e:
            logger.warning(f"No-roles check failed: {e}")

        # Determine overall risk level
        if findings["critical"]:
            overall = "🔴 CRITICAL"
        elif findings["high"]:
            overall = "🟠 HIGH"
        elif findings["medium"]:
            overall = "🟡 MEDIUM"
        else:
            overall = "🟢 LOW"

        # Build summary
        total = sum(len(v) for v in findings.values())

        output = f"🛡️ SAP Security Risk Assessment\n"
        output += f"{'=' * 50}\n\n"
        output += f"Overall Risk Level: {overall}\n"
        output += f"Total Findings: {total}\n"
        output += f"  Critical: {len(findings['critical'])}\n"
        output += f"  High:     {len(findings['high'])}\n"
        output += f"  Medium:   {len(findings['medium'])}\n"
        output += f"  Low:      {len(findings['low'])}\n\n"

        if findings["critical"]:
            output += "🔴 CRITICAL FINDINGS:\n"
            for f in findings["critical"]:
                output += f"  • {f}\n"
            output += "\n"

        if findings["high"]:
            output += "🟠 HIGH FINDINGS:\n"
            for f in findings["high"]:
                output += f"  • {f}\n"
            output += "\n"

        if findings["medium"]:
            output += "🟡 MEDIUM FINDINGS:\n"
            for f in findings["medium"]:
                output += f"  • {f}\n"
            output += "\n"

        if findings["low"]:
            output += "🟢 LOW FINDINGS:\n"
            for f in findings["low"]:
                output += f"  • {f}\n"
            output += "\n"

        output += "─" * 50 + "\n"
        output += "Generated by SyntaAI SAP Security MCP Server (OData Edition)\n"

        return output
